environment:
  ANDROID_HOME: "C:\\android-sdk-windows"
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"

clone_folder: "C:\\projects\\CallerInfo"

init:
  - set TEXT=I_AM_PUBLIC_AND_NOT_USED_FOR_RELEASE
  - set encrypted_151cd4732554_key="12CF1B5E0D192628AA922230549EEDFD889E6CF7463933C6DABD9A1300FCA23D"
  - set encrypted_151cd4732554_iv="66813CF28D04CD129D57436B78DECBA4"
 
  - set KEYSTORE_PASSWORD=%TEXT%
  - set ALIAS_PASSWORD=%TEXT%
  - set ALIAS=%TEXT%
 
  - mv "public.tar.enc" "secrets.tar.enc"

  - openssl aes-256-cbc -K "%encrypted_151cd4732554_key%" -iv "%encrypted_151cd4732554_iv%" -in secrets.tar.enc -out secrets.tar -d

  - tar xvf secrets.tar

  - git submodule update --init --recursive
  - cd \
  - appveyor DownloadFile http://dl.google.com/android/android-sdk_r24.4.1-windows.zip
  - 7z x android-sdk_r24.4.1-windows.zip > nul
  - cd C:\projects\CallerInfo

install:
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t platform-tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t build-tools-27.0.3
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t android-28
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-google-m2repository
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-android-m2repository


build_script:
  - gradlew.bat clean assembleDebug

artifacts:
  - path: "**\*.apk"

cache:
  - "%USERPROFILE%\\.m2"
  - "%USERPROFILE%\\.gradle"
