image: xdtianyu/openjdk8:latest

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - build
build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - "**/build/outputs/**/*.apk"
