name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: checkout submodule
      run: git submodule sync --recursive && git submodule update --init --recursive

    - uses: xdtianyu/actions-android-ci@master
    - name: before build
      run: '"
        source .travis/env.sh;
        openssl aes-256-cbc -K $encrypted_75846693d905_key -iv $encrypted_75846693d905_iv -in secrets.tar.enc -out secrets.tar -d;
        tar xvf secrets.tar;
        touch local.properties
        "'

    - uses: xdtianyu/actions-android-ci@master
    - name: build
      run: '"
        source .travis/env.sh;
        source /opt/setup-android-sdk.sh;
        ./gradlew assembleDebug
        "'
